import React from "react";

export default class IoTBlog extends React.Component {
  render() {
    return (
      <div id="blogContainer">
        <div id="blogHeader">
          <div id="blogTitle">
            <h2> IoT - What the Heck is it? Why Should You Care?</h2>
          </div>
          <div id="blogDate">
            <h3> November 18th, 2017</h3>
          </div>
        </div>
        <div id="blogContent">
        <span style="font-weight: 400;">The Internet of Things. We're starting to hear this phrase more and more. But haven't there always been things on the Internet? Well, that's not exactly what this term is referring to. Let's take a closer look at what the Internet of Things actually is, some of the many different current and future applications, how it will affect our lives, and how it's already been making its way into legislation.</span>
        <h2><b>Brief Explanation of the Internet of Things.</b></h2>
        <a href="https://www.postscapes.com/internet-of-things-definition/"><span style="font-weight: 400;">The Internet of Things</span></a><span style="font-weight: 400;"> generally refers to the infrastructure that allows various devices to connect to the internet and to each other.  These connected devices --</span><a href="http://www.crn.com/slide-shows/internet-of-things/300083379/20-crazy-connected-iot-products-at-ces-2017.htm/pgno/0/1"> <span style="font-weight: 400;">examples</span></a><span style="font-weight: 400;"> include FitBit, Alexa, Nest -- collect, transmit and process data to perform functions aimed at improving our overall quality of life. Devices that are considered part of "IoT" are not usually full-fledged computers, but rather purpose-built technologies which have computing power, sensors of some kind, and the ability to communicate with other systems or devices. On the consumer side, these devices tend towards collecting personal data and are unintrusive, though there are many </span><a href="https://www.ibm.com/blogs/internet-of-things/iot-applications-industries/"><span style="font-weight: 400;">other potential applications</span></a><span style="font-weight: 400;">.</span>

        <span style="font-weight: 400;">When you think about the Internet of Things, or IoT, and how it is the "next big thing", you need to think even bigger. Very few people can actually conceptualize exactly how big of a role IoT will play in our future. First, there are many, many definitions and terms that mean more or less the same thing when it comes to IoT; terms like </span><a href="https://www.iotforall.com/ambient-intelligence-ami-iot-use-cases/"><span style="font-weight: 400;">ambient intelligence,</span></a><a href="https://www.techopedia.com/definition/22702/ubiquitous-computing"> <span style="font-weight: 400;">ubiquitous computing,</span></a><a href="http://cyberphysicalsystems.org/"> <span style="font-weight: 400;">cyber physical systems</span></a><span style="font-weight: 400;"> and machine-to-machine (M2M) are all related to the IoT and to the technology and applications behind it.</span>
        <h2><b>Let's Go on a Little Hypothetical Trip in the World of IoT</b></h2>
        <span style="font-weight: 400;">Imagine a world where your whole entire house is "smart". This means everything from beds to closets to fridges to countertops is a connected device. In a normal morning, your bed would take into account when you fell asleep, how well you slept and your normal morning habits to wake you up when you are in your lightest level of sleep, so you wake up refreshed but have enough time to do everything on your morning agenda.</span>

        <span style="font-weight: 400;">Your closet then picks out your exercise clothes for the morning and steams and lays out your work clothes for after. You go to the kitchen and eat your last banana, which your countertop senses and puts bananas on your grocery list (which will be delivered later that day, via drone). Your water bottle is already waiting for you, poured to the perfect temperature and the thermostat in your gym is set to keep you from passing out from overheating. You have your favorite show to run to on, set to the perfect volume and playing when you enter your gym where you left off last.</span>

        <span style="font-weight: 400;">Your house knows how long you take at the gym, so the water for your shower has already been heated to the appropriate temperature and is ready for you to jump in - no more waiting for the water to warm up. You get out of the shower and have a reminder waiting on your mirror that you have twenty-five minutes to get ready if you want to catch your train. After you go through your morning checklist, get dressed and grab your already ready for you coffee, your smartwatch buzzes telling you the sensors in the concrete on the bridge on the way to the train indicate ice. As you approach the bridge, your car automatically slows down to navigate the dangerous terrain safely. You enter the parking garage and hop out to get on the train while your car parks itself or perhaps drives off to fetch another commuter. You walk into the train and your seat has a sensor that picks up your ID and knows you have a pass so there is no need to check your ticket. Just another day in the life!</span>
        <h2><b>Okay Now We Have a General Idea, What Potential Concerns do People Have Regarding IoT?</b></h2>
        <span style="font-weight: 400;">I sat down for an interview with Dr. Gilad L. Rosner, Founder of the </span><a href="http://www.iotprivacyforum.org"><span style="font-weight: 400;">Internet of Things Privacy Forum</span></a><span style="font-weight: 400;">, and had a very, very interesting conversation about the future of IoT and concerns we should keep in mind around privacy and security. I have listed my questions and paraphrased his answers for clarity and length.</span>

        <i><span style="font-weight: 400;">Q: What are the biggest issues you face with your overall company mission of reducing privacy risk with IoT?</span></i>
        <p style="padding-left: 30px;"><span style="font-weight: 400;">It is hard because we are in the early days of IoT, many people haven't even heard of IoT, nevertheless consider the privacy concerns associated with the new technologies. The major goal is to move the discussion surrounding privacy and IoT from small conversations within the privacy community to larger, more diverse conversations with the general public and the industries making this stuff. We need to get these conversations to the people who will be making product design  choices soon.</span></p>
        <p style="padding-left: 30px;"><span style="font-weight: 400;">There are two different major issues, economic and structural, when it comes to security. Structurally, figuring out how to lock down the data collected IoT from theft is very difficult. These devices can also be used as a platform to attack. </span><a href="https://dyn.com/blog/dyn-analysis-summary-of-friday-october-21-attack/"><span style="font-weight: 400;">The Dyn Attack</span></a><span style="font-weight: 400;"> in October of 2016 proved connected devices could be hacked and used for attack. Pretty much what happened is hackers used something called a distributed denial-of-service (DDoS) attack by requesting a large number of DNS lookups from tens of millions of IP addresses. Devices acted as the </span><a href="https://us.norton.com/botnet/"><span style="font-weight: 400;">botnet</span></a><span style="font-weight: 400;"> (connected devices running one more bots infected and controlled by a common type of malware) and were able to infiltrate and infect many devices connected to the internet like: printers, IP cameras, residential gateways and baby monitors with the Mirai malware.</span></p>
        <p style="padding-left: 30px;"><span style="font-weight: 400;">Economically, the problem of security is hard to address. Better security usually costs more and if a consumer cannot perceive benefits of security or if the benefits are not clearly communicated, consumers will buy the cheaper version. These are complicated topics, part of the challenge is the complexity of it all. At times, it is difficult to articulate privacy harms and address the strong discourse around the idea of people trading their personal data for convenience, services and products. This is a gross oversimplification of what is actually going on. People are being actively encouraged to share as much as possible, but for many reasons don’t necessarily have a sense of what a world would like with less sharing or where what they share is kept under better care.</span></p>
        <i><span style="font-weight: 400;">Q: What types of issues have you ran into spreading the word about where IoT is going and how important understanding the future and their roles as it pertains to our lives and privacy?</span></i>
        <p style="text-align: left; padding-left: 30px;"><span style="font-weight: 400;">The major questions to pose to people are, What else do the devices bring along with them aside from their obvious benefit of providing more data for more informed decisions? Who is looking out to ensure sure people cannot break into devices and use it?</span></p>
        <p style="text-align: left; padding-left: 30px;"><span style="font-weight: 400;">Giving consumers the maximum degree of choice for deciding how tech works and what information is shared is pivotal. </span></p>
        <p style="text-align: left; padding-left: 30px;"><span style="font-weight: 400;">An example of choice is the "wake word" for Alexa. Alexa is "always listening" for the wake word and then after it hears "Alexa" then it actively starts listening and transmitting. This "wakeup" is a design choice. What are the pressure points on manufacturers to ensure they implement these types of controls on their new devices even if the public does not know to ask for them? The ideal world is where products are designed in such a way that one person can choose to share all their information, another person chooses to share only a couple things and someone else  shares practically nothing . Standardizing how these devices protect privacy and enable selective sharing  before they become unremarkable is important. IoT is an evolution, not a revolution; they're simply evolved devices and another wave of computing.</span></p>
        &nbsp;

        <span style="font-weight: 400;">Gilad has been working with his research partner over the last year interviewing stakeholders and holding workshops to figure out the "freshest thinking" on this issue and where to go in the future. <a href="https://cdnapisec.kaltura.com/index.php/extwidget/preview/partner_id/684682/uiconf_id/33598632/entry_id/0_1cz8m7b9/embed/dynamic#t=03:00">Here</a> is a talk Gilad recent gave.</span>
        <h2><b>When it Comes to the Bills and Trends.</b></h2>
        <span style="font-weight: 400;">Privacy is a very compelling space when it comes to legislation. Dr. Rosner had some interesting insight into the fact that most of the privacy legislation is done at the local and state level, not the national level. That said, let's start by looking at the national level first.</span>

        <span style="font-weight: 400;">Think of past privacy frameworks, like the Consumer Privacy Bill of Rights, proposed by the Obama administration back in 2012. Since then, a few different privacy bills have been proposed but not enacted. Doesn't protecting citizens' privacy seem like a no-brainer?</span>

        <span style="font-weight: 400;">Although there are many different moving parts to what could affect IoT in legislation, one emerging trend is legislators separating explicit IoT legislation from privacy legislation. </span>

        <span style="font-weight: 400;">An intriguing national bill is the </span><a href="https://billtrack50.com/BillDetail/888345"><span style="font-weight: 400;">Black Box Privacy Protection Act.</span></a><span style="font-weight: 400;"> This act would require manufacturers to disclose to consumers the presence of event data recorders, (black boxes) on new automobiles, motorcycles and autocycles. It would also require manufacturers to provide the consumer with the option to enable and disable devices on future automobiles, motorcycles and autocycles.</span>

        <span style="font-weight: 400;">The</span><a href="https://billtrack50.com/BillDetail/761315"><span style="font-weight: 400;"> Cyber </span><span style="font-weight: 400;">Privacy Fortification Act of 2017,</span></a><span style="font-weight: 400;"> similar to data breach acts, would amend the federal criminal code to provide criminal penalties for intentional failures to provide required notices regarding security breaches of computerized data if there is reason to believe the breach resulted in improper access to specified sensitive, personally identifiable electronic or digital information. Although you can think of this more as a tool to punish something like the Equifax breach, it could be applied to IoT-related data too.</span>

        <a href="https://billtrack50.com/BillDetail/888545"><span style="font-weight: 400;">US S1691</span></a><span style="font-weight: 400;"> was introduced in August of 2017, titled the Internet of Things (IoT) Cybersecurity Improvement Act. This bill seeks to address vulnerabilities in IoT devices, which experts have long warned poses a threat to global cybersecurity. To do this, the bill requires vendors who provide internet-connected equipment to the U.S. government to ensure their products are patchable and conform to industry security standards. It would also prohibit vendors from supplying devices that have unchangeable passwords or possess known security vulnerabilities.</span>

        <span style="font-weight: 400;">Another interesting bill, </span><a href="https://billtrack50.com/BillDetail/860924"><span style="font-weight: 400;">SPY Car Act of 2017 Security and Privacy in Your Car Act of 2017</span></a><span style="font-weight: 400;">, to protect consumers from security and privacy threats to their motor vehicles. This act is expected to play a critical role in creating a fully secure in-vehicle cybersecurity system, currently non-existent. This bill also will force automakers to develop a “Detection, Reporting, and Responding to hacking” measure.</span>

        <a href="https://billtrack50.com/BillDetail/633933/6028"><span style="font-weight: 400;">Data Security and Breach Notification Act of 2015</span></a><span style="font-weight: 400;"> would have required certain commercial entities and non-profit organizations that use, access, transmit, store, dispose of, or collect unencrypted nonpublic personal information to restore the integrity, security and confidentiality of their data systems following the discovery of a security breach. This means they would have had to notify: affected U.S. residents when there is a reasonable risk of identity theft, economic harm or financial fraud, the Federal Trade Commission (FTC) and the U.S. Secret Service and consumer reporting agencies (if more than 10,000 people were affected), but the bill failed.</span>

        <span style="font-weight: 400;">The good thing is that about 40 states already have this type of data security legislation in place,</span><a href="http://www.ncsl.org/research/telecommunications-and-information-technology/security-breach-notification-laws.aspx"> <span style="font-weight: 400;">here</span></a><span style="font-weight: 400;"> is a list of different state's laws. And below is a list of IoT related bills introduced in the states this year:</span>

        <div id="BT50Widget"></div>
        &nbsp;
        <h2><b> Conclusion</b></h2>
        <span style="font-weight: 400;">It's easy to get swept up in the promise and excitement of this new technology. We've been promised "smart homes" for years, for decades even, but it seems the technology may have finally arrived. But we can't afford to lose sight of the risks of this technology as well. I think Dr. Rosner is right to want to establish good practices and norms now, while the technology is still young and inchoate. The right balance between cost and benefit for security and privacy features may not yet be obvious, but we should be demanding thoughtful policies as the number of these devices, and the information they are gathering, explodes. Experts, companies, consumers, and the government all have important roles to play as we hurtle into our highly connected future.</span>        </div>
      </div>
    );
  }
}
